MessageBoardClient/Models/Post.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;

namespace MessageBoardClient.Models
{
  public class Post
  {
    public int PostId { get; set; }
    public int UserId { get; set; }
    public User User { get; set; }
    public string Title { get; set; }
    public string PostBody { get; set; }
    public DateTime CreationDate { get; set; }
    public int ParentThreadId { get; set; }
    public Thread ParentThread { get; set; }

    public static List<Post> GetAll()
    {
      var apicallTask = ApiHelper.GetAll("posts");
      var result = apicallTask.Result;

      JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
      List<Post> postList = JsonConvert.DeserializeObject<List<Post>>(jsonResponse.ToString());

      return postList;
    }

    public static Post GetDetails(int id)
    {
      var apiCallTask = ApiHelper.Get("posts", id);
      var result = apiCallTask.Result;

      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      Post post = JsonConvert.DeserializeObject<Post>(jsonResponse.ToString());

      return post;
    }

    public static void NewPost(Post thisPost, int threadId)
    {
      string jsonPost = JsonConvert.SerializeObject(thisPost);
      var apiCallTask = ApiHelper.PostChild("threads", threadId, "posts", jsonPost);
    }

    public static void Put(Post post)
    {
      string jsonPost = JsonConvert.SerializeObject(post);
      var apiCallTask = ApiHelper.Put("posts", post.PostId, jsonPost);
    }

    public static void Delete(int id)
    {
      var apiCallTask = ApiHelper.Delete("posts", id);
    }
  }
}

MessageBoardClient/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MessageBoardClient.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace MessageBoardClient.Controllers
{
  public class PostsController : Controller
  {
    public IActionResult Index()
    {
      List<Post> allPosts = Post.GetAll();
      return View(allPosts);
    }

    public IActionResult Details(int id)
    {
      Post thisPost = Post.GetDetails(id);
      return View(thisPost);
    }

    public IActionResult Create(int threadId)
    {
      ViewBag.ThreadId = threadId;
      return View();
    }

    [HttpPost]
    public IActionResult Create(Post post, int threadId)
    { 
      post.ParentThreadId = threadId;
      Post.NewPost(post, threadId);
      return RedirectToAction("Details", "Threads", new { id = post.ParentThreadId });
    }

    public IActionResult Update(int id)
    {
      Post thisPost = Post.GetDetails(id);
      return View(thisPost);
    }

    [HttpPost]
    public IActionResult Update(Post post)
    {
      Post.Put(post);
      return RedirectToAction("Details", "Threads", new { id = post.ParentThreadId });
    }

    public IActionResult Delete(int id)
    {
      Post thisPost = Post.GetDetails(id);
      return View(thisPost);
    }

    [HttpPost]
    public IActionResult Delete(Post post)
    {
      Post.Delete(post.PostId);
      return RedirectToAction("Details", "Threads", new { id = post.ParentThreadId });
    }
  }
}

MessageBoardClient/Views/Posts/Create.cshtml
@model MessageBoardClient.Models.Post

@using (Html.BeginForm("Create", "Posts", new { threadId = ViewBag.ThreadId }))
{
  @Html.LabelFor(p => p.Title)
  @Html.TextBoxFor(p => p.Title)
  @Html.LabelFor(p => p.PostBody)
  @Html.TextBoxFor(p => p.PostBody)
  <input type="submit" value="Add Post" class="btn btn-primary" />
}

MessageBoardClient/Views/Posts/Delete.cshtml
@model MessageBoardClient.Models.Post

@using (Html.BeginForm())
{
  @Html.HiddenFor(p => p.PostId)
  @Html.HiddenFor(p => p.UserId)
  @Html.HiddenFor(p => p.Title)
  @Html.HiddenFor(p => p.PostBody)
  @Html.HiddenFor(p => p.CreationDate)
  @Html.HiddenFor(p => p.ParentThreadId)
  <input type="submit" value="Confirm Delete" class="btn btn-warning" />
}

MessageBoardClient/Views/Posts/Update.cshtml
@model MessageBoardClient.Models.Post

@using (Html.BeginForm())
{
  @Html.HiddenFor(p => p.PostId)
  @Html.LabelFor(p => p.Title)
  @Html.TextBoxFor(p => p.Title)
  @Html.LabelFor(p => p.PostBody)
  @Html.TextBoxFor(p => p.PostBody)
  <input type="submit" value="Update Post" class="btn btn-secondary" />
}