MessageBoardClient/Models/Board.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System;

namespace MessageBoardClient.Models
{
  public class Board
  {
    public int BoardId { get; set; }
    public string Title { get; set; }
    public ICollection<Thread> Threads { get; set; }

    public Board()
    {
      this.Threads = new HashSet<Thread>();
    }

    public static List<Board> GetAll()
    {
      var apiCallTask = ApiHelper.GetAll("boards");
      var result = apiCallTask.Result;

      JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
      List<Board> boardList = JsonConvert.DeserializeObject<List<Board>>(jsonResponse.ToString());

      return boardList;
    }

    public static Board GetDetails(int id)
    {
      var apiCallTask = ApiHelper.Get("boards", id);
      var result = apiCallTask.Result;

      JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
      Board board = JsonConvert.DeserializeObject<Board>(jsonResponse.ToString());

      return board;
    }

    public static void Post(Board board)
    {
      string jsonBoard = JsonConvert.SerializeObject(board);
      var apiCallTask = ApiHelper.Post("boards", jsonBoard);
    }

    public static void Put(Board board)
    {
      string jsonBoard = JsonConvert.SerializeObject(board);
      var apiCallTask = ApiHelper.Put("boards", board.BoardId, jsonBoard);
    }

    public static void Delete(int id)
    {
      var apiCallTask = ApiHelper.Delete("boards", id);
    }
  }
}

MessageBoardClient/Controllers/BoardsController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using MessageBoardClient.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using System.Threading.Tasks;

namespace MessageBoardClient.Controllers
{
  public class BoardsController : Controller
  {
    public IActionResult Index()
    {
      List<Board> allBoards = Board.GetAll();
      return View(allBoards);
    }

    public IActionResult Details(int id)
    {
      Board thisBoard = Board.GetDetails(id);
      return View(thisBoard);
    }

    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public IActionResult Create(Board board)
    {
      Board.Post(board);
      return RedirectToAction("Index");
    }

    public IActionResult Update(int id)
    {
      Board thisBoard = Board.GetDetails(id);
      return View(thisBoard);
    }

    [HttpPost]
    public IActionResult Update(Board board)
    {
      Board.Put(board);
      return RedirectToAction("Index");
    }

    public IActionResult Delete(int id)
    {
      Board thisBoard = Board.GetDetails(id);
      return View(thisBoard);
    }

    [HttpPost]
    public IActionResult Delete(Board board)
    {
      Board.Delete(board.BoardId);
      return RedirectToAction("Index");
    }
  }
}

MessageBoardClient/Controllers/ThreadsController.cs
using MessageBoardClient.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MessageBoardClient.Controllers
{
  public class ThreadsController : Controller
  {
    public IActionResult Index()
    {
      List<Thread> allThreads = Thread.GetAll();
      return View(allThreads);
    }

    public IActionResult Details(int id)
    {
      Thread thisThread = Thread.GetDetails(id);
      return View(thisThread);
    }

    public IActionResult Create(int boardId)
    {
      ViewBag.BoardId = boardId;
      return View();
    }

    [HttpPost]
    public IActionResult Create(Thread thread, int boardId)
    {
      thread.ParentBoardId = boardId;
      thread.CreationDate = DateTime.Now;
      thread.UserId = 1;
      Thread.Post(thread, boardId);
      return RedirectToAction("Details", "Boards", new { id = thread.ParentBoardId });
    }

    public IActionResult Update(int id)
    {
      Thread thisThread = Thread.GetDetails(id);
      return View(thisThread);
    }

    [HttpPost]
    public IActionResult Update(Thread thread)
    {
      Thread.Put(thread);
      return RedirectToAction("Details", new { id = thread.ThreadId });
    }

    public IActionResult Delete(int id)
    {
      Thread thread = Thread.GetDetails(id);
      return View(thread);
    }

    [HttpPost]
    public IActionResult Delete(Thread thread)
    {
      Thread.Delete(thread.ThreadId);
      return RedirectToAction("Details", "Boards", new { id = thread.ParentBoardId });
    }
  }
}

MessageBoardClient/Views/Boards/Create.cshtml
@model MessageBoardClient.Models.Board

@using (Html.BeginForm())
{
@Html.LabelFor(model => model.Title)
@Html.TextBoxFor(model => model.Title)
<input type="submit" value="Add board" class="btn btn-primary" />
}

MessageBoardClient/Views/Boards/Delete.cshtml
@model MessageBoardClient.Models.Board

@using (Html.BeginForm())
{
  @Html.HiddenFor(b => b.BoardId)
  @Html.HiddenFor(b => b.Title)
  <input type="submit" value="Confirm Delete" class="btn btn-warning" />
}

MessageBoardClient/Views/Boards/Details.cshtml
@using MessageBoardClient.Models
@model MessageBoardClient.Models.Board

<h1>@Html.DisplayFor(b => b.Title)</h1>

<ul>
  @foreach(Thread thread in Model.Threads)
  {
    <li>@Html.ActionLink($"{thread.Title}", "Details", "Threads", new { id= thread.ThreadId })</li>
  }
</ul>

<p>@Html.ActionLink("Post A New Thread", "Create", "Threads", new { boardId = Model.BoardId })</p>
<p>@Html.ActionLink("Back To Board Index", "Index", "Boards")</p>

MessageBoardClient/Views/Boards/Index.cshtml
@model List<MessageBoardClient.Models.Board>;
@using MessageBoardClient.Models;

<ul>
@foreach (Board board in Model)
{
  <li>@Html.ActionLink($"{board.Title}", "Details", "Boards", new {id = board.BoardId}), Threads: @board.Threads.Count </li>
}

@Html.ActionLink($"Add board", "Create", "Boards")

MessageBoardClient/Views/Boards/Update.cshtml
@model MessageBoardClient.Models.Board

@using (Html.BeginForm())
{
  @Html.HiddenFor(b => b.BoardId)
  @Html.LabelFor(b => b.Title)
  @Html.TextBoxFor(b => b.Title)
  <input type="submit" value="Update Title" class="btn btn-secondary" />
}